import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/components/providers";
//import { ConnectButton } from "@rainbow-me/rainbowkit";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: ReactNode;
};
//const queryClient = new QueryClient();

const Layout = ({ children }: LayoutProps) => {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-black">
        <Providers>
          <Header />
          {/*<main className="flex-1 pt-16 relative items-center justify-center min-h-screen">*/}
          {children}
          {/*</main>*/}
          <Toaster />
          <Footer />
        </Providers>
      </body>
    </html>
  );
};

export { metadata };
export default Layout;
