import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/components/providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: ReactNode;
};
//const queryClient = new QueryClient();

const Layout = ({ children }: LayoutProps) => {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex items-center justify-center min-h-screen bg-black">
            {/*<div className="bg-white p-8 rounded-lg shadow-md w-full max-w-md"> */}
            {children}
            <Toaster />
            {/*</div> */}
          </div>
        </body>
      </Providers>
    </html>
  );
};

export { metadata };
export default Layout;
